simple-server
DanielDavidyan/simple-server pull request #1
Opened 2022-03-13 08:55 UTC by DanielDavidyan

2022-03-13 14:42 UTC, rongoldinfeld requested changes

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +fs.readFile(contentPath, 'utf-8', (err, data) => {
Extract to a util folder and file
This function executes at the start of the server. What happens if i change the file 2 days after the server is up? This should be called on each request

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +    content = data.toUpperCase();
What happens when this file is large? You are reading the whole file to the RAM. For example if data is 20GB, your server will probably will crash. Read about streams and implement.

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +fs.stat(packageJsonPath, (err, stats) => {
Extract to a util folder and file
This function executes at the start of the server. What happens if i change the file 2 days after the server is up? This should be called on each request. 
Wrap as new Promise

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +    if (postUrl === '/content') {
Adding more requests will make this if else statement huge. Can u think of another way?

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +    let postUrl = req.url;
You do not verify the request method. This two request will work for all methods: GET, POST, PUT…

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +const http = require('http');
No types? Add types for request, variables, an so on. 
Use `import {} from …`

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +}).listen(8080);
Add the ability to start server port by environment variables

2022-03-13 14:42 UTC, rongoldinfeld commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
How do u run this server? Add scripts for server start, and remove empty test script

2022-03-13 14:42 UTC, rongoldinfeld commented on server.ts
> +const dirPath = '/Users/danieldavidyan/Documents/ofek/server/simple-server/';
If i ran this server of facebook server will it work? Why?

2022-03-13 14:50 UTC, DanielDavidyan commented on server.ts
> +const dirPath = '/Users/danieldavidyan/Documents/ofek/server/simple-server/';
No, because it is local url.

2022-03-13 14:53 UTC, rongoldinfeld commented on server.ts
> +const dirPath = '/Users/danieldavidyan/Documents/ofek/server/simple-server/';
How do u solve this?

2022-03-16 07:15 UTC, DanielDavidyan commented on server.ts
> +}).listen(8080);
Read about node environment variables

2022-04-03 08:55 UTC, rongoldinfeld requested changes

2022-04-03 08:55 UTC, rongoldinfeld commented on package.json
> +    "start": "npx ts-node server.ts"
what is npx

2022-04-03 08:55 UTC, rongoldinfeld commented on server.ts
> +const PORT = process.env.PORT || 8080;
port, and see how you run it

2022-04-03 08:55 UTC, rongoldinfeld commented on utilities/server.utils.ts
> +async function getContent(res: any) {
fix res type

2022-04-03 08:55 UTC, rongoldinfeld commented on utilities/file-system.ts
> +export async function statAsync(path: PathLike = contentPath): Promise<any> {
any type

2022-04-03 08:55 UTC, rongoldinfeld commented on utilities/file-system.ts
> +    return (await promises.stat(path)).mtime.toString();
use fs.stat without promises, and use new Promise()

2022-04-03 08:55 UTC, rongoldinfeld commented on server.ts
> +    if (requestsResolver[<string>postUrl] && req.method === 'GET') {
nested requests resolver to avoid multiple ifs

2022-04-03 08:55 UTC, rongoldinfeld commented on server.ts
> +http.createServer(function (req: IncomingMessage, res: ServerResponse) {
deal with 404-  not found

2022-04-03 08:55 UTC, rongoldinfeld commented on server.ts
> +    res.writeHead(200);
should we call it? what happens on bad request? not found?

2022-04-24 07:20 UTC, rongoldinfeld approved these changes

2022-04-24 07:20 UTC, merged